'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.544
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace SerRef1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="SerRef1.IMath")>  _
    Public Interface IMath
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMath/add", ReplyAction:="http://tempuri.org/IMath/addResponse")>  _
        Function add(ByVal num1 As Integer, ByVal num2 As Integer) As Long
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMath/subtract", ReplyAction:="http://tempuri.org/IMath/subtractResponse")>  _
        Function subtract(ByVal num1 As Integer, ByVal num2 As Integer) As Long
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IMathChannel
        Inherits SerRef1.IMath, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class MathClient
        Inherits System.ServiceModel.ClientBase(Of SerRef1.IMath)
        Implements SerRef1.IMath
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function add(ByVal num1 As Integer, ByVal num2 As Integer) As Long Implements SerRef1.IMath.add
            Return MyBase.Channel.add(num1, num2)
        End Function
        
        Public Function subtract(ByVal num1 As Integer, ByVal num2 As Integer) As Long Implements SerRef1.IMath.subtract
            Return MyBase.Channel.subtract(num1, num2)
        End Function
    End Class
End Namespace
